name: Security Checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  antivirus:
    name: Antivirus Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ClamAV and run scan
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav
          clamscan -r .
      - name: Add label
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: sec-passed

  bandit:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r .

  pylint:
    name: Pylint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pylint
        run: pip install pylint
      - name: Run Pylint
        run: pylint *.py || true
